apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: espace-game-dirag
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.db
              name: volume
